language: node_js
sudo: required
node_js: 
  - 15.14.0

branches:
  only:
    - hexo 

before_install:
  - npm i hexo-cli -g

# S: Build Lifecycle
install:
  - npm i
  - npm i hexo-deployer-git --save
  - npm i Mime --save

before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "ChiRenhua"
  - git config user.email "crh944015688@163.com"
  - sed -i "s/repo_token/${REPO_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy
